### ISSUE TITLE
您好 请问你遇到过pcm 编码 AAC比较耗时的问题吗

### ISSUE THREAD

**Issue by CodeK1988** [gezhaoyou/AndroidAACEncoder#2]
您好  我这边要实现 多段pcm 指定位置 混合插入一段背景音乐aac 中。 因为pcm 指定位置混合 ffmpeg 不支持 或者说我没有找到方法。 于是 我先将 背景音乐aac 转码 pcm . 这个过程比较快。再   录音 将多段pcm指定位置 和 背景音乐 pcm 混合。  得到一个全新的pcm. 在将pcm 转码 aac .但这个时候 需要十几秒的时间。 我觉得可能是 多段pcm 做混合的时候 产生了一些重复的垃圾字节。 转码的时候 比较耗时。我用的是这个 compile 'com.github.adrielcafe:AndroidAudioConverter:0.0.8'。 可以给一些建议吗？ pcm 编码 aac 比较慢的问题。 谢谢~

**Comment by parkergrt** [comment]
因为业务没有这方面的需求，所以暂时没有遇到过这个问题。你可以比较相同长度混合前和混合后的pcm转码时间，确定下是否是pcm拼接的问题，其他的暂时帮不上忙了，给你个音视频开发Q群：256061378，可以去里面问下 :）

**Comment by CodeK1988** [comment]
谢谢~
